require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.1
  NewCops: enable

  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/**/*'

Style/Documentation:
  Enabled: false